services:

  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - '5437:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
